### ISSUE TITLE
Exported symbol "expand_path" breaks sway with duplicate symbol error

### ISSUE THREAD

**Issue by tbwLcFm5uXcAeQ** [xkbcommon/libxkbcommon#827]
Exported symbol `expand_path`, introduced in #818, conflicts with a [similarly named symbol](https://github.com/swaywm/sway/blob/e50b16a69969d136595efe2b595cf55c9cef39fb/common/stringop.c#L314) in sway.

https://github.com/xkbcommon/libxkbcommon/blob/d60b3213362f22933275a902e9c4c561a1e2674d/src/xkbcomp/include.c#L270-L273

**Comment by bluetech** [comment]
@tbwLcFm5uXcAeQ What is the meson invocation you are using to build sway?
